export const MODIFY_PLAYER_HEALTH = "MODIFY_PLAYER_HEALTH";
export const MODIFY_MONSTER_HEALTH = "MODIFY_MONSTER_HEALTH";
export const MODIFY_PLAYER_DAMAGE = "MODIFY_PLAYER_DAMAGE";
export const MODIFY_MONSTER_DAMAGE = "MODIFY_MONSTER_DAMAGE";
export const MONSTER_DAMAGE_DEALT = "MONSTER_DAMAGE_DEALT";
export const PLAYER_DAMAGE_DEALT = "PLAYER_DAMAGE_DEALT";
export const NEW_GAME = "NEW_GAME";
